### ISSUE TITLE
Milestone 2: UI side panel with interactive widget inputs

### ISSUE THREAD

**Issue by Lorraine97** [UBC-MDS/climadash#13]
https://github.com/UBC-MDS/climadash/blob/main/img/Dashboard_Sketch_Climate.png

- [x] Dropdown for city selection
- [x] Year range filter
- [x] Data radio to select between precipitation and temperature
